### ISSUE TITLE
architecture improvements

### ISSUE THREAD

**Issue by errordeveloper** [kelseyhightower/kargo#1]
There are probably various ways to go about this, here is my take to get the discussion started.

First of all, I think it's probably a good idea to start by using a 3rd-party API resource.

Let's assume we have something like this:
```YAML
apiVersion: "github.com/kelseyhightower/kargo"
kind: SelfManagedApp
metadata:
    name: {{ .Name }}
    labels:
        version: {{ .Version }}
payload:
    binaryData: {{ .BinaryData }}
    args: {{ .Args }}
    env: {{ .Env }}
replicas: {{ .Replicas }}
controller: Deployment
baseImage: alpine:latest
```

On startup, an app that uses this library would create this resource in Kubernetes API and fill-out the template with runtime data, including binary itself, given arguments and environment variables, name, version and other metadata.

A `SelfManagedApp` controller running in the cluster will converts `payload` to an image and make that image available on all nodes (there may exist a `DaemonSet` to help this process, which could be running an image registry or something simpler, like `docker load` wrapper, whatever). Once images are built, the controller would apply `Deployment` definition based on `replicas` and `metadata` etc.

It seems like the above should be enough, am I missing anything?
